# Generated by Django 5.1.1 on 2024-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
