# Generated by Django 5.1.1 on 2024-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_city_description_city_population_alter_city_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('start_city', 'end_city'), name='unique_route'),
        ),
    ]
